export const GET_FORECASTS = "Forecast/GET_FORECASTS"
export const GET_FORECASTS_LOADING = "Forecast/GET_FORECASTS_LOADING"
export const GET_FORECASTS_LOADED = "Forecast/GET_FORECASTS_LOADED"
export const GET_FORECASTS_FAILED = "Forecast/GET_FORECASTS_FAILED"

export const FILTER_BY_LOCATION = "Forecast/FILTER_BY_LOCATION"
export const FILTER_BY_LOCATION_LOADING = "Forecast/FILTER_BY_LOCATION_LOADING"
export const FILTER_BY_LOCATION_LOADED = "Forecast/FILTER_BY_LOCATION_LOADED"
export const FILTER_BY_LOCATION_FAILED = "Forecast/FILTER_BY_LOCATION_FAILED"
